Vagrant.configure("2") do |config|
  
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "n3.local"
  config.vm.network "public_network", ip: '192.168.1.54', :bridge => 'en0: Wi-Fi' #,type: "dhcp",
  #config.vm.network "private_network", ip: "192.168.50.7", virtualbox__intnet: "nodenw"
  
end
