Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.hostname = "pnd2"
    config.vm.network "public_network", ip: '10.0.0.121', :bridge => 'en0: Wi-Fi' #,type: "dhcp" 
    #config.vm.network "private_network", ip: "192.168.50.7", virtualbox__intnet: "nodenw"
    
  end
  
  #Vagrant  notes
  # /vagrant dor inside the VM will map to folder on host that contains the vagrant 
