Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.hostname = "pnd1"  
    config.vm.network "public_network", ip: '10.0.0.120', :bridge => 'en0: Wi-Fi' #,type: "dhcp" 
  end
  
  #Vagrant  notes
  # /vagrant dor inside the VM will map to folder on host that contains the vagrant 
  
  # Install docker
  # sudo apt-get update
  # sudo apt-get install ca-certificates curl gnupg lsb-release

  # sudo mkdir -p /etc/apt/keyrings
  # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  # sudo apt-get update
  # sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

  # sudo usermod -aG docker vagrant
